### ISSUE TITLE
Punkte-Eingabe

### ISSUE THREAD

**Issue by Baridiane** [funditsch/doppelkopf#2]
Punkte Eingabe auf gültigen (Ganz-)Zahlenwert prüfen.

Frau Edith sagt: also auf dem Smartphone ist die Eingabe doch bereits, wie man es sich vorstellt, denn man hat nur die Möglichkeit eine ganze Zahl einzugeben. Es muss nur noch die leere Eingabe abgefangen werden.

Keine Ahnung, ob das so elegant ist, aber das hilft:

isValid(): boolean {
        const countWon = this.state.players.filter(p => p.status.status === GameStatusEnum.WON).length;
        const countLost = this.state.players.filter(p => p.status.status === GameStatusEnum.LOST).length;
        const stateCheck = (this.state.value)?true:false;
        return ((countWon === 2 && countLost === 2) ||
            (countWon === 1 && countLost === 3) ||
            (countWon === 3 && countLost === 1)) && stateCheck;
    }

**Comment by funditsch** [comment]
wenn man prüft ob der Wert gesetzt ist, dann kann man auch gleich prüfen ob es ne gültige Zahl ist (vielleicht kann ja auf nem Android doch Buchstaben oder Kommazahlen eingeben?). Daher hab ich Number.isInteger(Number.parseFloat(this.state.value)) genommen
